- hosts: localhost
  tasks:
  - name: install git
    become: yes
    become_method: sudo
    yum: name=git state=latest
  - name: clone petclinic
    git:
     repo: https://github.com/VeredA/spring-petclinic.git
     dest: ~/petclinic
  - name: clone ciscocd
    git:
     repo: https://github.com/VeredA/ciscocd.git
     dest: ~/ciscocd 
     
