- hosts: localhost
  tasks:
  - name: install git
    become: yes
    become_method: sudo
    yum: name=git state=latest
  - name: clone petclinic
    git:
     repo: https://github.com/VeredA/spring-petclinic.git
     dest: ~/petclinic
  - name: clone ciscocd
    git:
     repo: https://github.com/VeredA/ciscocd.git
     dest: ~/ciscocd 
     update: no 
  - name: download maven
    get_url:
      url: http://www-us.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
      dest: ~/ciscocd
  - name: unarchive
    unarchive:
      src: apache-maven-3.3.9-bin.tar.gz
      dest: ~/ciscocd
